### ISSUE TITLE
网页版上的链接问题

### ISSUE THREAD

**Issue by shengbinmeng** [abolybook/aboly#1]
在《一瓶论语》网页版（<http://www.abolybook.org/aboly>）上点击每小节原文右边的章号会跳转到《论语》（<http://www.abolybook.org/ly>）页面上的相应章节。

这是本就设计如此吗？我期望的是在同一本书内部跳转。

（另外，反过来在《论语》页面上点章号又会跳转到《一瓶论语》；这个还可以算是前往详细解释，勉强说的通。）

**Comment by abolybook** [comment]
多谢反馈！如果您是指类似这样的章号：

![1](https://cloud.githubusercontent.com/assets/12606298/21477658/c9bb5502-cb7e-11e6-858f-0136270668ec.png)

确实就是原本的设计。基本想法是：有时看注释版觉得太罗嗦，想跳到白文版清净一阵；有时看原文不太明白，又想直接跳到有注释的对应处。

在同一本书内跳转，建议用整个页面右上角的这个按钮，会弹出一个下拉菜单，显示全书目录：

![2](https://cloud.githubusercontent.com/assets/12606298/21477692/2528b36c-cb7f-11e6-897c-bbf1058dc649.png)

这些在[“Web版上线啦！”](http://www.abolybook.org/web-edition)里面略有说明，现在想想还应该加在本项目的Wiki里。

便捷的交叉链接，是这个小项目（包括PDF版、Web版）诞生之初就确立的宗旨。欢迎多多尝试，继续提供宝贵建议。:sunny:

**Comment by shengbinmeng** [comment]
> 如果您是指类似这样的章号

没错，是指这个。

> 这些在“Web上线啦！”里面略有说明

啊，我没仔细看这个说明，不好意思。

现在明白了不是bug。不过我还是觉得保持一本书的独立性为好。

**Comment by shengbinmeng** [comment]
嗯，我想了想这样的设计也挺好。而且本来就处在这个小节了，再跳转到同一个地方倒也没意义。

**Comment by abolybook** [comment]
是的，我当初也在“自包含”和“大串联”之间斟酌了一阵，各有取舍。希望现在这样既实用又不惹人烦。:smile:
