### ISSUE TITLE
对于学而的思考

### ISSUE THREAD

**Issue by keepquiet** [abolybook/aboly#2]
十分佩服您的逐字逐句式翻译工作。我在其他地方也看到觉得刚合适一些翻译：
“例如清代学者焦循就引《论语》7.8、6.21及11.22支持他的说法，以“合时”来解释“时”字。他说：“当其可之谓时。说，解悦也。”大多数六朝及宋代学者则倾向另一种解释，如皇侃认为，“时”指的是“所学并日日修习（‘年中’与‘身中’）不暂废也”。我选择焦循的解释，与公元前四世纪时孟子形容孔子是“圣之时者”有关。孟子相信“圣之时”高于“圣之清”与“圣之任”，认为合乎时的行动是“学”的极致——孔子教导的“学”，不只是知识的堆积，而是能成于“仁”，达到“修齐治平”与道德审美的境界。有了这样的学问，就可以招徕远方之人，即使“人不知”也“不愠”，因为是为了自己而学。”
摘录来自论语英译及评注：汉、英【美】金安平, 鄢秀
写出来与你分享套路一下。

**Comment by abolybook** [comment]
感谢您的建议！《一瓶论语》对“时”的解释是“按时，时常”，前一个“按时”也是想容纳“合时”的意义，就是兼有on schedule（按固定的时间）和in due time（按恰当的时间）。本来觉得用“以时”会更到位，但可惜比较远离现代文。所以后面再用timely对应了一下，是希望：

- 突出at the right time这方面的含义。
- 更一般地，点出汉语与英语的相通及差异。
  - 形式上，名词“时”对应于“time”，汉语副词仍然是“时”，英语副词则要有词形变化“timely”（它更多用作形容词）。灵活的词性是汉字的一大特点，我在撰写的时候也时常注意，比如《使用说明·体例》及1.8对“无”的举例都有涉及。
  - 意义上，二者的本义并不相同，“时”源自四时节令，“时间”是其较早的引申义，引申面也更有弹性，比如可以指水果鲜美当令（10.8“不时，不食”）。如果把《辞源》、《汉字源流字典》的词条仔细读一遍，会更容易体会汉字的这个特点。也可以只考虑“时间”这一支的意义，与牛津词典（ODE）中“time”及其衍生词的所有含义进行比较，会发现无论词性词义如何左冲右突，令人拍案称奇，也始终不离“时”、“time”之根，都是“可以理解的”，并感受到汉语、英语在含义派生方面的脑洞大小。

大体而言，添加英文解释的情况要么是含义特别精当，要么是本义和引申义有共通之处，否则就变成浪费篇幅的中译英了，让人很难忍受。

“当其可之谓时”出自《礼记·学记》，焦循《孟子正义·公孙丑上》曾予引用。“时”、“习”等概念在汉、晋、唐、宋、明、清等时代的解释几经颠扑，往往因时而变、因派有别，对于现代的一般读者来说，实际意义未必很大。我想达到的效果，是以《论语》文本、孔子本身为准，参考代表性、有影响的著作观点，给出扎实可用、最好还略有启发的解释；愿意深究的读者看过各家之说后，最好仍会觉得《一瓶论语》的说法“大体尚可”。《论语》文字简练，汉语的灵活性又大，很容易有不同的理解。我的策略是抓住本义，提供依据，启发思考，反对迷信，“辞达而已矣”。孟子的风格一往无前，后人对孔子的评价经常偏于玄虚、诠释过多、总结性过强，这种我采纳得比较谨慎，总觉得不如多注意些反映孔子人性光辉、可感可学的实处。

国外学者的研究成果，我也尽量学习，可惜水平有限，只能看英文材料。《论语》的英译本我用到的大致有Legge、Waley、辜鸿铭、刘殿爵、Brooks、Slingerland、Schiller这几种，多谢您提供的参考。中英对照特别有意思，经常会碰到文化差异产生的奇特视角，王京涛还有一本对辜鸿铭译本再回译的著作。从Amazon看，刘殿爵、金安平、Slingerland都排在前列。我上次调研的时候，最流行的是Slingerland，然而有明显的疏忽。个人最赞赏的是Schiller，一字一钉，用力很深。金安平的作品我读过广西师大引进的《孔子：喧嚣时代的孤独哲人》，感觉很符合国外作者的风格，观点独到，奇趣迭出，不过可引用性、小心求证的功力略弱，这跟传统著作讲究的圆融精熟是挺好的互补。
